name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          dnf install -y cmake gcc-c++ clang llvm \
            libX11-devel libXcursor-devel libXinerama-devel \
            libXrandr-devel libXi-devel mesa-libGL-devel mesa-libGLU-devel

      - name: Print Tools Verion
        run: |
          cmake --version
          ${{ matrix.compiler }} --version

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.compiler }}
          cmake --build build

  build-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Print Tools Verion
        run: |
          cmake --version
          cl --version

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl

      - name: Build
        run: cmake --build build
